on: push
name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.cluster129.hosting.ovh.net
          username: mesvoyh
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          # On déploie à la racine de votre projet sur OVH
          server-dir: /www/mesvoyages/ 
          # On exclut les dossiers inutiles pour gagner du temps
          exclude: |
            **/.git*
            **/tests/**
            .gitignore